export enum ApplicationRoutes {
  HOME = "/",
  MODULE_ONE = "/module-one",
  MODULE_TWO = "/modulo-dois",
  MODULE_TWO_EXAMPLE_ONE = "/modulo-dois/exemplo-um",
  MODULE_TWO_EXAMPLE_TWO = "/modulo-dois/exemplo-dois",
  MODULE_TWO_EXAMPLE_THREE = "/modulo-dois/exemplo-tres",
  MODULE_TWO_EXAMPLE_FOUR = "/modulo-dois/exemplo-quatro",
  MODULE_TWO_EXAMPLE_FIVE = "/modulo-dois/exemplo-cinco",
  MODULE_THREE = "/modulo-tres",
  MODULE_THREE_EXAMPLE_ONE = "/modulo-tres/exemplo-um",
  MODULE_THREE_EXAMPLE_TWO = "/modulo-tres/exemplo-dois",
  MODULE_THREE_EXAMPLE_THREE = "/modulo-tres/exemplo-tres",
  MODULE_THREE_EXAMPLE_FOUR = "/modulo-tres/exemplo-quatro",
  MODULE_FOUR = "/modulo-quatro",
  MODULE_FOUR_EXAMPLE_ONE = "/modulo-quatro/exemplo-um",
  MODULE_FOUR_EXAMPLE_TWO = "/modulo-quatro/exemplo-dois",
  MODULE_FIVE = "/modulo-cinco",
  MODULE_FIVE_EXAMPLE_ONE = "/modulo-cinco/exemplo-um",
  MODULE_FIVE_EXAMPLE_TWO = "/modulo-cinco/exemplo-dois",
  MODULE_FIVE_EXAMPLE_THREE = "/modulo-cinco/exemplo-tres",
  MODULE_FIVE_EXAMPLE_FOUR = "/modulo-cinco/exemplo-quatro",
  MODULE_SIX = "/module-six",
  MODULO_SETE = "/modulo-sete",
  MODULO_SETE_EXEMPLO_CYPRESS = "/modulo-sete/exemplo1-cypress",
  MODULO_SETE_EXEMPLO1_TESTE_UNITARIO = "/modulo-sete/exemplo1-teste-unitario",
  MODULO_SETE_EXEMPLO2_TESTE_UNITARIO = "/modulo-sete/exemplo2-teste-unitario",
}
